services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auction
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - auction-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d auction']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - auction-network
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    image: auction/api
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auction?schema=public
      - REDIS_URL=redis://redis:6379
    networks:
      - auction-network
  worker:
    build: .
    image: auction/worker
    command: pnpm run start:worker
    depends_on:
      - redis
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auction?schema=public
      - REDIS_URL=redis://redis:6379
    networks:
      - auction-network

volumes:
  pgdata:
  redisdata:

networks:
  auction-network:
