services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - auction-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - auction-network

  api:
    build: .
    image: auction/api
    restart: always
    depends_on:
      - redis
      - db
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    networks:
      - auction-network
  worker:
    build: .
    image: auction/worker
    command: pnpm run start:worker
    depends_on:
      - redis
    restart: always
    env_file:
      - ./.env
    networks:
      - auction-network

volumes:
  pgdata:
  redisdata:

networks:
  auction-network:
    name: auction_default
    external: true
